[target.thumbv7em-none-eabihf]
runner = ['nwlink', 'install-nwa']
rustflags = [
    "-C",
    "link-arg=--relocatable",
    "-C",
    "link-arg=-no-gc-sections",
    "-C",
    "target-cpu=cortex-m7",
]

[build]
target = "thumbv7em-none-eabihf"
