[package]
name = "numworks_utils"
version = "0.2.5"
edition = "2021"

[lib]
name = "numworks_utils"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.8.0"

[build-dependencies]
cc = "*"
