[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C",
    "link-arg=--relocatable",
    "-C",
    "link-arg=-no-gc-sections",
    "-C",
    "target-cpu=cortex-m7",
]
